### ISSUE TITLE
MMOLib causing MMOCore NullPointerException: null on start-up.

### ISSUE THREAD

**Issue by mibby** [mmopluginteam/mmolib#3]
MythicMobs-4.10.0-SNAPSHOT dev 3342
MMOItems-5.5.3-SNAPSHOT dev 288
MMOCore-1.4.2-SNAPSHOT dev 213
MMOLib 1.2.4

The recent mmolib update is not compatible with the latest dev builds for mmo plugins. It causes an explosion of errors due to mmocore not being able to load.

NullPointerException: null around quests.

https://paste.gg/p/anonymous/60fe9b5c60cd405fba3b504b77312a3a/files/441c9618d6384f378de374dc356c27a7/raw

```
[16:15:25] [Server thread/ERROR]: Error occurred while enabling MMOCore v1.4.2-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: null
	at net.Indyuce.mmocore.api.quest.Quest.<init>(Quest.java:57) ~[?:?]
	at net.Indyuce.mmocore.manager.QuestManager.load(QuestManager.java:24) ~[?:?]
	at net.Indyuce.mmocore.manager.QuestManager.lambda$load$0(QuestManager.java:21) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
	at net.Indyuce.mmocore.manager.QuestManager.load(QuestManager.java:21) ~[?:?]
	at net.Indyuce.mmocore.manager.QuestManager.lambda$load$0(QuestManager.java:21) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
	at net.Indyuce.mmocore.manager.QuestManager.load(QuestManager.java:21) ~[?:?]
	at net.Indyuce.mmocore.manager.QuestManager.reload(QuestManager.java:49) ~[?:?]
	at net.Indyuce.mmocore.MMOCore.reloadPlugin(MMOCore.java:410) ~[?:?]
	at net.Indyuce.mmocore.MMOCore.onEnable(MMOCore.java:251) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Tuinity-"014232b"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Tuinity-"014232b"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Tuinity-"014232b"]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Tuinity-"014232b"]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Tuinity-"014232b"]
	at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.1.jar:git-Tuinity-"014232b"]
	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:242) ~[patched_1.16.1.jar:git-Tuinity-"014232b"]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940) ~[patched_1.16.1.jar:git-Tuinity-"014232b"]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Tuinity-"014232b"]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

Downgrading to MMOLib 1.2.3, start-up is fine again.

https://paste.gg/p/anonymous/a7b41b419ece4046ba4680b2a5d1df81/files/f42c6aedb9d6447790bedc2d0498889e/raw

**Comment by Joshinn-mc** [comment]
Not able to replicate this, you might have an underlying issue elsewhere. Could you past a full log?

**Comment by mibby** [comment]
That is a full log..

**Comment by ASangarin** [comment]
Seems to be an error with your quests.
Try backing them up and loading it up with the default quests on latest versions.

**Comment by mibby** [comment]
Using the newer public released builds, there doesn't seem to be any start-up error anymore. So not sure if it was just a random oddity or the dev builds were just incompatible until it was recompiled against the new lib version.

MMOCore-1.4.2.
MMOItems-5.5.3
MMOLib-1.2.4

Since this doesn't seem to be an issue anymore, I'll be closing this. :)
